language: python

python:
  - pypy
  - pypy3
  - 2.6
  - 2.7
  - 2.7_with_system_site_packages
  - 3.2
  - 3.3
  - 3.4

install:
  - pip install -r requirements.txt

script:
  - python satellite_pies.py

after_success:
  - pip install flake8
  - pep8 *.py
  - pyflakes *.py
